noun1=input("Enter a noun:")
body_part=input("Enter a body part:")
noun2=input("Enter a noun:")
animal=input("Enter an animal:")
verb=input("Enter a verb:")
catch_phrase=input("Enter a catch phrase:")
emotion=input("Enter an emotion:")
adj=input("Enter an adjective:")
verb2=input("Enter a verb:")
plural_noun=input("Enter a plural noun:")
verb3=input("Enter a verb:")
location=input("Enter a location:")
body_part2=input("Enter a body part:")
adj2=input("Enter an adjective:")
emotion2=input("Enter an emotion:")
adverb=input("Enter an adverb:")
song_title=input("Enter a song title:")
verb3=input("Enter a verb:")
animal2=input("Enter an animal:")
print("When Philip met Jasmine, it was " + noun1 + " at first sight." + "He couldn't believe his " + body_part+"!")
print("She smelled like " + noun2 + " and walked as graceful as a " + animal+".")
print("He " + verb + " over to say " + catch_phrase + " and introduced himself.")
print("She was so " + emotion +"!")
print("She has seen him around and thought he was super " + adj+".")
print("They " + verb2 +" for a while and then exchanged " + plural_noun+".")
print("On their first date, they " + verb3 + " at the " + location + " and he couldn't keep his " + body_part2 + " off her.")
print("After a " + adj2 + " night, he was " + emotion2 + " to bring her home.")
print("She " + adverb + " looked at him and said " + song_title + " and he just knew, he had to " + verb3 + " her again.")
print("Since then, they have been inseparable and he started calling her his " +animal2+".")